yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow',
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow',
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls import handler403, handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('group_list/', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from core.models import CreationDateModel
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Название группы', max_length=200)
    slug = models.SlugField(
        max_length=255,
        unique=True,
        db_index=True,
        verbose_name='Идентификатор ссылки',
        help_text='Введите короткое слово на английском',
    )
    description = models.TextField('Описание группы')

    def __str__(self):
        return self.title


class Post(CreationDateModel):
    text = models.TextField('Текст записи', help_text='Введите ваш текст')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор записи',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа записи',
        help_text='Выберите группу',
    )
    image = models.ImageField('Картинка', upload_to='posts/', blank=True)

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'


class Comment(CreationDateModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментируемая запись',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
    )
    text = models.TextField('Комментарий', help_text='Введите ваш текст')

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Подписки',
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_follow'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post

User = get_user_model()


def _create_page_obj(request, post_set):
    """Создает коллекцию постов для пагинатора."""
    paginator = Paginator(post_set, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


def index(request):
    """Обрабатывает главную страницу."""
    post_set = Post.objects.select_related('group', 'author').all()
    page_obj = _create_page_obj(request, post_set)
    context = {
        'page_obj': page_obj,
        'index': True,
        'follow': False,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Обрабатывает страницу с фильтрацией постов по группе."""
    group = get_object_or_404(Group, slug=slug)
    post_set = group.posts.prefetch_related('author')
    page_obj = _create_page_obj(request, post_set)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Обрабатывает страницу автора."""
    author = get_object_or_404(User, username=username)
    post_set = author.posts.select_related('group')
    page_obj = _create_page_obj(request, post_set)
    following = Follow.objects.filter(
        author=author.id, user=request.user.id
    ).exists()
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """Обрабатывает страницу опубликованного поста."""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """Обрабатывает страницу и форму создания поста."""
    form = PostForm(request.POST or None, files=request.FILES)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.author = request.user
        instance.save()
        return redirect('posts:profile', username=request.user)
    return render(
        request, 'posts/create_post.html', {'form': form, 'is_edit': False}
    )


@login_required
def post_edit(request, post_id):
    """Обрабатывает редактирование ранее созданного поста."""
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(instance=post)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    """Обрабатывает добавление комментария."""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect('posts:post_detail', post_id=post_id)
    return render(request, 'posts/create_post.html', context={"form": form})


@login_required
def follow_index(request):
    """Обрабатывает страницу с фильтрацией постов по подпискам."""
    post_set = Post.objects.filter(author__following__user=request.user).all()
    page_obj = _create_page_obj(request, post_set)
    context = {
        'page_obj': page_obj,
        'index': False,
        'follow': True,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Обрабатывает подписку на пользователя."""
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=author.username)


@login_required
def profile_unfollow(request, username):
    """Обрабатывает отписку от пользователя."""
    author = get_object_or_404(User, username=username)
    subscribe = Follow.objects.filter(
        author=author.id, user=request.user.id
    ).all()
    if subscribe.exists():
        subscribe.delete()
    return redirect('posts:profile', username=author.username)

yatube/templates/includes/comments.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-3">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}

<nav class="navbar navbar-dark" style="background-color: Teal">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img 
        src="{% static 'img/logo.png' %}" 
        width="30" 
        height="30" 
        class="d-inline-block align-top" 
        alt="">
      <span style="color:red">Ya</span>tube</a>
    </a>

    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
      <li class="nav-item"> 
        <a 
          class="nav-link 
            {% if view_name  == 'about:author' %}active bg-dark{% endif %} link-light" 
          href="{% url 'about:author' %}">
            Об авторе
        </a>
      </li>
      <li class="nav-item">
        <a 
          class="nav-link 
            {% if view_name  == 'about:tech' %}active bg-dark{% endif %} link-light"
          href="{% url 'about:tech' %}">
            Технологии
        </a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item"> 
        <a 
          class="nav-link 
            {% if view_name  == 'posts:post_create' %}active bg-dark{% endif %} link-light"
          href="{% url 'posts:post_create' %}">
            Новая запись
        </a>
      </li>
      <li class="nav-item"> 
        <a 
          class="nav-link 
            {% if view_name  == 'users:password_change' %}active bg-dark{% endif %} link-light"
          href="{% url 'users:password_change' %}">
            Изменить пароль
        </a>
      </li>
      <li class="nav-item"> 
        <a 
          class="nav-link 
            {% if view_name  == 'users:logout' %}active bg-dark{% endif %} link-light"
          href="{% url 'users:logout' %}">
            Выйти
        </a>
      </li>
      <li>
        Пользователь: {{ user.username }}
      </li>
      {% else %}
      <li class="nav-item"> 
        <a 
          class="nav-link 
            {% if view_name  == 'users:login' %}active bg-dark{% endif %} link-light"
          href="{% url 'users:login' %}">
            Войти
        </a>
      </li>
      <li 
        class="nav-item"> 
        <a class="nav-link 
          {% if view_name  == 'users:signup' %}active bg-dark{% endif %} link-light"
        href="{% url 'users:signup' %}">
          Регистрация
        </a>
      </li>
      {% endif %}
      {% endwith %}
    </ul>
  </div>
</nav>

yatube/templates/includes/post.html
{% load thumbnail %}
<article class="card" style="margin-bottom: 30px;">
  <ul class="list-group">
  {% if not author %}  
    <li class="list-group-item bg-light">
      Автор: 
      <a href="{% url 'posts:profile' post.author.username %}">
        {{ post.author.get_full_name }}
      </a>
    </li>
    {% endif %}
    <li class="list-group-item bg-light">
      Дата публикации: {{ post.created|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img-top my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <div class="card-text px-5">
    <p>{{ post.text|linebreaks }}</p>
  </div>
  <div class="card-footer">
    <a 
      style="margin-right: 10px;" 
      class="btn btn-sm btn btn-outline-primary" 
      href="{% url 'posts:post_detail' post.pk %}"
    >
      Подробная информация
    </a>
    {% if post.group and not group.slug %}  
      <a 
        class="btn btn-sm btn btn-outline-primary" 
        href="{% url 'posts:group_list' post.group.slug %}"
      >
        Все записи группы: {{ post.group.title }}
      </a>
    {% endif %}
  </div>
</article>